title: Adam Takeuchi
email: amtakeuchi1@gmail.com
description: "Cybersecurity Portfolio, Cloud Projects, and Blog"
baseurl: ""
url: "https://amtakeuchi.netlify.app"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

paginate: 5
paginate_path: "/blog/page:num/"

color_scheme: dark

repository: amtakeuchi/portfolio
