title: Securi-tee 
email: amtakeuchi1@gmail.com
description: "Cybersecurity Portfolio, Tech Projects, and Blog"
baseurl: ""
url: "https://amtakeuchi.netlify.app"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

color_scheme: dark

sass:
  style: compressed

repository: amtakeuchi/portfolio
